# Generated by Django 4.1.2 on 2024-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='best_players',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='good_players',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='is_reimplementation',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_alternates',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_comments',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_expansions',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_implementations',
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='language_ease',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
