# Generated by Django 4.1.2 on 2024-04-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_remove_boardgame_best_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='com_age_rec',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='com_max_playtime',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='com_min_playtime',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='family',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='mfg_age_rec',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='mfg_playtime',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_owned',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_user_ratings',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_want',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_weight_votes',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='num_wish',
        ),
    ]
