# Generated by Django 4.1.2 on 2024-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_remove_boardgame_com_age_rec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='com_age_rec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
