# Generated by Django 4.1.2 on 2024-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_boardgame_com_age_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
