# Generated by Django 4.1.2 on 2024-04-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0006_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
